schema = 3

[mod]
[mod."charm.land/fang/v2"]
version = "v2.0.1"
hash = "sha256-gDGetHyMJIYiAWeUjgyESKwIZyE0HJTGcyrmZLE+h/E="
[mod."charm.land/lipgloss/v2"]
version = "v2.0.1"
hash = "sha256-W0N53P08vNGYbk2nSt5iePFvwTEUpHzEIU+HHtWx2yE="
[mod."github.com/adrg/xdg"]
version = "v0.5.3"
hash = "sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs="
[mod."github.com/charmbracelet/colorprofile"]
version = "v0.4.2"
hash = "sha256-AMnmwWjpv/TMb2mbqVXB4RmMVWBsrTFlq1FL8A00olw="
[mod."github.com/charmbracelet/ultraviolet"]
version = "v0.0.0-20260205113103-524a6607adb8"
hash = "sha256-zHe+nAS80nJPgZ4c3mU2HcHA9QL486b0BiyC4FNK3Nk="
[mod."github.com/charmbracelet/x/ansi"]
version = "v0.11.6"
hash = "sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI="
[mod."github.com/charmbracelet/x/exp/charmtone"]
version = "v0.0.0-20250603201427-c31516f43444"
hash = "sha256-x6EfMobGGF31tnkjXuoGLxAa6V1ozsR2Z43TQu9/mX0="
[mod."github.com/charmbracelet/x/term"]
version = "v0.2.2"
hash = "sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4="
[mod."github.com/charmbracelet/x/termios"]
version = "v0.1.1"
hash = "sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds="
[mod."github.com/charmbracelet/x/windows"]
version = "v0.2.2"
hash = "sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk="
[mod."github.com/clipperhouse/displaywidth"]
version = "v0.11.0"
hash = "sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo="
[mod."github.com/clipperhouse/uax29/v2"]
version = "v2.7.0"
hash = "sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE="
[mod."github.com/davecgh/go-spew"]
version = "v1.1.1"
hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
[mod."github.com/gofrs/flock"]
version = "v0.13.0"
hash = "sha256-5imm90Iqstu+PnSX9RLZMHUG7qW2KX2t3xIpZ2cXSco="
[mod."github.com/google/renameio/v2"]
version = "v2.0.2"
hash = "sha256-Z/6OUS9T9tCMm9nJLrMXUQ6cq3FiV/rS7v9/AYNkA7I="
[mod."github.com/inconshreveable/mousetrap"]
version = "v1.1.0"
hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
[mod."github.com/kr/text"]
version = "v0.2.0"
hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
[mod."github.com/lucasb-eyer/go-colorful"]
version = "v1.3.0"
hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
[mod."github.com/mattn/go-runewidth"]
version = "v0.0.20"
hash = "sha256-Y3qYfCqPt+Ce/MEk8dr6pSdd1ZwO2Nwm5sjLIbw26TY="
[mod."github.com/muesli/cancelreader"]
version = "v0.2.2"
hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
[mod."github.com/muesli/mango"]
version = "v0.1.0"
hash = "sha256-Xy63UxeZJMU4JlG6uuEpUeyxTGytx+NDbqCAgXpZrrU="
[mod."github.com/muesli/mango-cobra"]
version = "v1.2.0"
hash = "sha256-26X9H9t2Z/kLII2n/Zd+D568H2rlbVJPS11jT25bdUA="
[mod."github.com/muesli/mango-pflag"]
version = "v0.1.0"
hash = "sha256-qgUxVjVFmbcGjn8m58DRRu4hmYhirEUDy9TjkJYU8m4="
[mod."github.com/muesli/roff"]
version = "v0.1.0"
hash = "sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA="
[mod."github.com/pmezard/go-difflib"]
version = "v1.0.0"
hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
[mod."github.com/rivo/uniseg"]
version = "v0.4.7"
hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
[mod."github.com/rogpeppe/go-internal"]
version = "v1.14.1"
hash = "sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E="
[mod."github.com/spf13/cobra"]
version = "v1.10.2"
hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
[mod."github.com/spf13/pflag"]
version = "v1.0.9"
hash = "sha256-YAjyYpq5BXCosVJtvYLWFG1t4gma2ylzc7ILLoj/hD8="
[mod."github.com/stretchr/testify"]
version = "v1.11.1"
hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
[mod."github.com/xo/terminfo"]
version = "v0.0.0-20220910002029-abceb7e1c41e"
hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
[mod."golang.org/x/sync"]
version = "v0.19.0"
hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
[mod."golang.org/x/sys"]
version = "v0.42.0"
hash = "sha256-LhNedvUEJbPYyR6EoU91rfOr3DBBoauLOcMcyqghEos="
[mod."golang.org/x/text"]
version = "v0.24.0"
hash = "sha256-qFbmteGOvJfvbLXiOSI8Fsz5Ixt2ZhSYx0/sIqApC7Y="
[mod."gopkg.in/yaml.v3"]
version = "v3.0.1"
hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
